# Generated by Django 5.1.6 on 2025-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pregunta_opcion_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha_votacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date votacion'),
        ),
    ]
